/* Generated By:JJTree: Do not edit this line. ASTbnf_production.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTbnf_production extends JJNode {
  public ASTbnf_production(int id) {
    super(id);
  }

  public ASTbnf_production(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=623ce79f73a253e4d524c4543c1c22b1 (do not edit this line) */
