/* Generated By:JJTree: Do not edit this line. ASTbnf_production.java */

package sf.eclipse.javacc.parser;

public class ASTbnf_production extends JJNode {
  public ASTbnf_production(int id) {
    super(id);
  }

  public ASTbnf_production(JavaCCParser p, int id) {
    super(p, id);
  }

}
