/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
class ASTClassOrInterfaceDeclaration extends JJNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=0be9b478709699fccbf6b8f2eef86b96 (do not edit this line) */
