/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java */

package sf.eclipse.javacc.parser;

public class ASTClassOrInterfaceDeclaration extends JJNode {
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(JavaCCParser p, int id) {
    super(p, id);
  }

}
