/* Generated By:JJTree: Do not edit this line. ASTident_use.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTident_use extends JJNode {
  public ASTident_use(int id) {
    super(id);
  }

  public ASTident_use(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=aa8c0ea91a59b704c075dee0cd77da79 (do not edit this line) */
