/* Generated By:JJTree: Do not edit this line. ASTident_bnf_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTident_bnf_decl extends JJNode {
  public ASTident_bnf_decl(int id) {
    super(id);
  }

  public ASTident_bnf_decl(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=654b80be0b34b31833cffe8a25da9442 (do not edit this line) */
