/* Generated By:JJTree: Do not edit this line. ASTident_reg_expr_private_label.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTident_reg_expr_private_label extends JJNode {
  public ASTident_reg_expr_private_label(int id) {
    super(id);
  }

  public ASTident_reg_expr_private_label(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4e36da8fd8e4cfc040820856c606b235 (do not edit this line) */
