/* Generated By:JJTree: Do not edit this line. ASTident_bnf_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTident_bnf_decl extends JJNode {
  public ASTident_bnf_decl(int id) {
    super(id);
  }

  public ASTident_bnf_decl(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3923333758c98401c776f221091f43c4 (do not edit this line) */
