/* Generated By:JJTree: Do not edit this line. ASTident_reg_expr_label.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTident_reg_expr_label extends JJNode {
  public ASTident_reg_expr_label(int id) {
    super(id);
  }

  public ASTident_reg_expr_label(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c7fe98a6ff044c362d46b68a3b52b7ae (do not edit this line) */
