/* Generated By:JJTree: Do not edit this line. ASTJavaIdentifierInClassOrInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTJavaIdentifierInClassOrInterfaceDeclaration extends JJNode {
  public ASTJavaIdentifierInClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTJavaIdentifierInClassOrInterfaceDeclaration(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=643c8dbe61800a0c33556f67cd7a2237 (do not edit this line) */
