/* Generated By:JJTree: Do not edit this line. ASTJavaIdentifierInMethodDeclarator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTJavaIdentifierInMethodDeclarator extends JJNode {
  public ASTJavaIdentifierInMethodDeclarator(int id) {
    super(id);
  }

  public ASTJavaIdentifierInMethodDeclarator(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7943837594f73c34083dc5d46fd92e92 (do not edit this line) */
