/* Generated By:JJTree: Do not edit this line. ASTjavacode_production.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTjavacode_production extends JJNode {
  public ASTjavacode_production(int id) {
    super(id);
  }

  public ASTjavacode_production(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=90d9820e02da2d568b9bf2fdd6c3bd55 (do not edit this line) */
