/* Generated By:JJTree: Do not edit this line. ASTjavacc_options.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTjavacc_options extends JJNode {
  public ASTjavacc_options(int id) {
    super(id);
  }

  public ASTjavacc_options(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d9ed23b4e963de56e7778921af182a16 (do not edit this line) */
