/* Generated By:JJTree: Do not edit this line. ASTMethodDeclaration.java */

package sf.eclipse.javacc.parser;

public class ASTMethodDeclaration extends JJNode {
  public ASTMethodDeclaration(int id) {
    super(id);
  }

  public ASTMethodDeclaration(JavaCCParser p, int id) {
    super(p, id);
  }

}
