/* Generated By:JJTree: Do not edit this line. ASTnode_desc_in_exp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTnode_desc_in_exp extends JJNode {
  public ASTnode_desc_in_exp(int id) {
    super(id);
  }

  public ASTnode_desc_in_exp(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b83507038f93c0e9c4651038d5c35cfc (do not edit this line) */
