/* Generated By:JJTree: Do not edit this line. ASTnode_desc_bnf_decl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTnode_desc_bnf_decl extends JJNode {
  public ASTnode_desc_bnf_decl(int id) {
    super(id);
  }

  public ASTnode_desc_bnf_decl(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=336f561dc6d91a29fa850c9f6de998d4 (do not edit this line) */
