/* Generated By:JJTree: Do not edit this line. ASTnode_desc_in_meth.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTnode_desc_in_meth extends JJNode {
  public ASTnode_desc_in_meth(int id) {
    super(id);
  }

  public ASTnode_desc_in_meth(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=158b16739a496ea82857841a04e653de (do not edit this line) */
