/* Generated By:JJTree: Do not edit this line. ASToption_binding.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASToption_binding extends JJNode {
  public ASToption_binding(int id) {
    super(id);
  }

  public ASToption_binding(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9e584c8c982f7493d4d0105c344ddd1a (do not edit this line) */
