/* Generated By:JJTree: Do not edit this line. ASToption_binding.java */

package sf.eclipse.javacc.parser;

public class ASToption_binding extends JJNode {
  public ASToption_binding(int id) {
    super(id);
  }

  public ASToption_binding(JavaCCParser p, int id) {
    super(p, id);
  }

}
