/* Generated By:JJTree: Do not edit this line. ASTparser_begin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTparser_begin extends JJNode {
  public ASTparser_begin(int id) {
    super(id);
  }

  public ASTparser_begin(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6ac6bd5c26109a2d20e0f81e91cdd561 (do not edit this line) */
