/* Generated By:JJTree: Do not edit this line. ASTparser_begin.java */

package sf.eclipse.javacc.parser;

public class ASTparser_begin extends JJNode {
  public ASTparser_begin(int id) {
    super(id);
  }

  public ASTparser_begin(JavaCCParser p, int id) {
    super(p, id);
  }

}
