/* Generated By:JJTree: Do not edit this line. ASTregexpr_kind.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTregexpr_kind extends JJNode {
  public ASTregexpr_kind(int id) {
    super(id);
  }

  public ASTregexpr_kind(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c127f092f02de5b4ce6a5c04b198894 (do not edit this line) */
