/* Generated By:JJTree: Do not edit this line. ASTroot.java */

package sf.eclipse.javacc.parser;

public class ASTroot extends JJNode {
  public ASTroot(int id) {
    super(id);
  }

  public ASTroot(JavaCCParser p, int id) {
    super(p, id);
  }

}
