/* Generated By:JJTree: Do not edit this line. ASTregular_expr_production.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
class ASTregular_expr_production extends JJNode {
  public ASTregular_expr_production(int id) {
    super(id);
  }

  public ASTregular_expr_production(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=56fb41472ca6c90432e4708d4712fd12 (do not edit this line) */
