/* Generated By:JJTree: Do not edit this line. ASTregexpr_spec.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
class ASTregexpr_spec extends JJNode {
  public ASTregexpr_spec(int id) {
    super(id);
  }

  public ASTregexpr_spec(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70f788698369d418b9a4af1e754d7ee2 (do not edit this line) */
