/* Generated By:JJTree: Do not edit this line. ASTroot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTroot extends JJNode {
  public ASTroot(int id) {
    super(id);
  }

  public ASTroot(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=384ac98781bbc5721d5d095320fe3a2c (do not edit this line) */
