/* Generated By:JJTree: Do not edit this line. ASTregular_expr_production.java */

package sf.eclipse.javacc.parser;

public class ASTregular_expr_production extends JJNode {
  public ASTregular_expr_production(int id) {
    super(id);
  }

  public ASTregular_expr_production(JavaCCParser p, int id) {
    super(p, id);
  }

}
