/* Generated By:JJTree: Do not edit this line. ASTregexpr_spec.java */

package sf.eclipse.javacc.parser;

public class ASTregexpr_spec extends JJNode {
  public ASTregexpr_spec(int id) {
    super(id);
  }

  public ASTregexpr_spec(JavaCCParser p, int id) {
    super(p, id);
  }

}
