/* Generated By:JJTree: Do not edit this line. ASTtoken_manager_decls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
class ASTtoken_manager_decls extends JJNode {
  public ASTtoken_manager_decls(int id) {
    super(id);
  }

  public ASTtoken_manager_decls(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=167df29c2d3d13f776f3a9051e5f4846 (do not edit this line) */
