/* Generated By:JJTree: Do not edit this line. ASTtoken_manager_decls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package sf.eclipse.javacc.parser;

public
@SuppressWarnings("all")
class ASTtoken_manager_decls extends JJNode {
  public ASTtoken_manager_decls(int id) {
    super(id);
  }

  public ASTtoken_manager_decls(JavaCCParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d18b3d0563146df268fdbff99fde35d8 (do not edit this line) */
