/* Generated By:JJTree&JavaCC: Do not edit this line. JavaCCParserConstants.java */
package sf.eclipse.javacc.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
@SuppressWarnings("all")
public interface JavaCCParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int _OPTIONS = 1;
  /** RegularExpression Id. */
  int _LOOKAHEAD = 2;
  /** RegularExpression Id. */
  int _IGNORE_CASE = 3;
  /** RegularExpression Id. */
  int _PARSER_BEGIN = 4;
  /** RegularExpression Id. */
  int _PARSER_END = 5;
  /** RegularExpression Id. */
  int _JAVACODE = 6;
  /** RegularExpression Id. */
  int _TOKEN = 7;
  /** RegularExpression Id. */
  int _SPECIAL_TOKEN = 8;
  /** RegularExpression Id. */
  int _MORE = 9;
  /** RegularExpression Id. */
  int _SKIP = 10;
  /** RegularExpression Id. */
  int _TOKEN_MGR_DECLS = 11;
  /** RegularExpression Id. */
  int _EOF = 12;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 22;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 23;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 24;
  /** RegularExpression Id. */
  int ABSTRACT = 26;
  /** RegularExpression Id. */
  int ASSERT = 27;
  /** RegularExpression Id. */
  int BOOLEAN = 28;
  /** RegularExpression Id. */
  int BREAK = 29;
  /** RegularExpression Id. */
  int BYTE = 30;
  /** RegularExpression Id. */
  int CASE = 31;
  /** RegularExpression Id. */
  int CATCH = 32;
  /** RegularExpression Id. */
  int CHAR = 33;
  /** RegularExpression Id. */
  int CLASS = 34;
  /** RegularExpression Id. */
  int CONST = 35;
  /** RegularExpression Id. */
  int CONTINUE = 36;
  /** RegularExpression Id. */
  int _DEFAULT = 37;
  /** RegularExpression Id. */
  int DO = 38;
  /** RegularExpression Id. */
  int DOUBLE = 39;
  /** RegularExpression Id. */
  int ELSE = 40;
  /** RegularExpression Id. */
  int ENUM = 41;
  /** RegularExpression Id. */
  int EXTENDS = 42;
  /** RegularExpression Id. */
  int FALSE = 43;
  /** RegularExpression Id. */
  int FINAL = 44;
  /** RegularExpression Id. */
  int FINALLY = 45;
  /** RegularExpression Id. */
  int FLOAT = 46;
  /** RegularExpression Id. */
  int FOR = 47;
  /** RegularExpression Id. */
  int GOTO = 48;
  /** RegularExpression Id. */
  int IF = 49;
  /** RegularExpression Id. */
  int IMPLEMENTS = 50;
  /** RegularExpression Id. */
  int IMPORT = 51;
  /** RegularExpression Id. */
  int INSTANCEOF = 52;
  /** RegularExpression Id. */
  int INT = 53;
  /** RegularExpression Id. */
  int INTERFACE = 54;
  /** RegularExpression Id. */
  int LONG = 55;
  /** RegularExpression Id. */
  int NATIVE = 56;
  /** RegularExpression Id. */
  int NEW = 57;
  /** RegularExpression Id. */
  int NULL = 58;
  /** RegularExpression Id. */
  int PACKAGE = 59;
  /** RegularExpression Id. */
  int PRIVATE = 60;
  /** RegularExpression Id. */
  int PROTECTED = 61;
  /** RegularExpression Id. */
  int PUBLIC = 62;
  /** RegularExpression Id. */
  int RETURN = 63;
  /** RegularExpression Id. */
  int SHORT = 64;
  /** RegularExpression Id. */
  int STATIC = 65;
  /** RegularExpression Id. */
  int STRICTFP = 66;
  /** RegularExpression Id. */
  int SUPER = 67;
  /** RegularExpression Id. */
  int SWITCH = 68;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 69;
  /** RegularExpression Id. */
  int THIS = 70;
  /** RegularExpression Id. */
  int THROW = 71;
  /** RegularExpression Id. */
  int THROWS = 72;
  /** RegularExpression Id. */
  int TRANSIENT = 73;
  /** RegularExpression Id. */
  int TRUE = 74;
  /** RegularExpression Id. */
  int TRY = 75;
  /** RegularExpression Id. */
  int VOID = 76;
  /** RegularExpression Id. */
  int VOLATILE = 77;
  /** RegularExpression Id. */
  int WHILE = 78;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 79;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 80;
  /** RegularExpression Id. */
  int HEX_LITERAL = 81;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 82;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 83;
  /** RegularExpression Id. */
  int EXPONENT = 84;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 85;
  /** RegularExpression Id. */
  int STRING_LITERAL = 86;
  /** RegularExpression Id. */
  int LPAREN = 87;
  /** RegularExpression Id. */
  int RPAREN = 88;
  /** RegularExpression Id. */
  int LBRACE = 89;
  /** RegularExpression Id. */
  int RBRACE = 90;
  /** RegularExpression Id. */
  int LBRACKET = 91;
  /** RegularExpression Id. */
  int RBRACKET = 92;
  /** RegularExpression Id. */
  int SEMICOLON = 93;
  /** RegularExpression Id. */
  int COMMA = 94;
  /** RegularExpression Id. */
  int DOT = 95;
  /** RegularExpression Id. */
  int ASSIGN = 96;
  /** RegularExpression Id. */
  int GT = 97;
  /** RegularExpression Id. */
  int LT = 98;
  /** RegularExpression Id. */
  int BANG = 99;
  /** RegularExpression Id. */
  int TILDE = 100;
  /** RegularExpression Id. */
  int HOOK = 101;
  /** RegularExpression Id. */
  int COLON = 102;
  /** RegularExpression Id. */
  int EQ = 103;
  /** RegularExpression Id. */
  int LE = 104;
  /** RegularExpression Id. */
  int GE = 105;
  /** RegularExpression Id. */
  int NE = 106;
  /** RegularExpression Id. */
  int SC_OR = 107;
  /** RegularExpression Id. */
  int SC_AND = 108;
  /** RegularExpression Id. */
  int INCR = 109;
  /** RegularExpression Id. */
  int DECR = 110;
  /** RegularExpression Id. */
  int PLUS = 111;
  /** RegularExpression Id. */
  int MINUS = 112;
  /** RegularExpression Id. */
  int STAR = 113;
  /** RegularExpression Id. */
  int SLASH = 114;
  /** RegularExpression Id. */
  int BIT_AND = 115;
  /** RegularExpression Id. */
  int BIT_OR = 116;
  /** RegularExpression Id. */
  int XOR = 117;
  /** RegularExpression Id. */
  int REM = 118;
  /** RegularExpression Id. */
  int SHARP = 119;
  /** RegularExpression Id. */
  int PLUSASSIGN = 120;
  /** RegularExpression Id. */
  int MINUSASSIGN = 121;
  /** RegularExpression Id. */
  int STARASSIGN = 122;
  /** RegularExpression Id. */
  int SLASHASSIGN = 123;
  /** RegularExpression Id. */
  int ANDASSIGN = 124;
  /** RegularExpression Id. */
  int ORASSIGN = 125;
  /** RegularExpression Id. */
  int XORASSIGN = 126;
  /** RegularExpression Id. */
  int REMASSIGN = 127;
  /** RegularExpression Id. */
  int IDENTIFIER = 133;
  /** RegularExpression Id. */
  int LETTER = 134;
  /** RegularExpression Id. */
  int PART_LETTER = 135;
  /** RegularExpression Id. */
  int ILLEGAL = 136;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"options\"",
    "\"LOOKAHEAD\"",
    "\"IGNORE_CASE\"",
    "\"PARSER_BEGIN\"",
    "\"PARSER_END\"",
    "\"JAVACODE\"",
    "\"TOKEN\"",
    "\"SPECIAL_TOKEN\"",
    "\"MORE\"",
    "\"SKIP\"",
    "\"TOKEN_MGR_DECLS\"",
    "\"EOF\"",
    "\" \"",
    "\"\\t\"",
    "\"\\r\\n\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"\\f\"",
    "\"//\"",
    "<token of kind 20>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 25>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"#\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"...\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"@\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<ILLEGAL>",
  };

}
