/* Generated By:JavaCC: Do not edit this line. JavaCCParserTreeConstants.java Version 5.0 */
package sf.eclipse.javacc.parser;

public interface JavaCCParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTROOT = 1;
  public int JJTPARSER_BEGIN = 2;
  public int JJTJAVACC_OPTIONS = 3;
  public int JJTOPTION_BINDING = 4;
  public int JJTJAVACODE_PRODUCTION = 5;
  public int JJTBNF_PRODUCTION = 6;
  public int JJTREGULAR_EXPR_PRODUCTION = 7;
  public int JJTTOKEN_MANAGER_DECLS = 8;
  public int JJTREGEXPR_SPEC = 9;
  public int JJTIDENTIFIER = 10;
  public int JJTCLASSORINTERFACEDECLARATION = 11;
  public int JJTMETHODDECLARATION = 12;


  public String[] jjtNodeName = {
    "void",
    "root",
    "parser_begin",
    "javacc_options",
    "option_binding",
    "javacode_production",
    "bnf_production",
    "regular_expr_production",
    "token_manager_decls",
    "regexpr_spec",
    "identifier",
    "ClassOrInterfaceDeclaration",
    "MethodDeclaration",
  };
}
/* JavaCC - OriginalChecksum=c706ef2a549303d764186c6ffcd20c3e (do not edit this line) */
