/* Generated By:JavaCC: Do not edit this line. JavaCCParserTreeConstants.java Version ??.?? */
package sf.eclipse.javacc.parser;

@SuppressWarnings("all")
public interface JavaCCParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTROOT = 1;
  public int JJTIDENT_USE = 2;
  public int JJTPARSER_BEGIN = 3;
  public int JJTJAVACC_OPTIONS = 4;
  public int JJTOPTION_BINDING = 5;
  public int JJTJAVACODE_PRODUCTION = 6;
  public int JJTBNF_PRODUCTION = 7;
  public int JJTIDENT_BNF_DECL = 8;
  public int JJTNODE_DESC_BNF_DECL = 9;
  public int JJTREGULAR_EXPR_PRODUCTION = 10;
  public int JJTTOKEN_MANAGER_DECLS = 11;
  public int JJTREGEXPR_KIND = 12;
  public int JJTREGEXPR_SPEC = 13;
  public int JJTNODE_DESC_IN_EXP = 14;
  public int JJTIDENT_REG_EXPR_LABEL = 15;
  public int JJTIDENT_REG_EXPR_PRIVATE_LABEL = 16;
  public int JJTCLASSORINTERFACEDECLARATION = 17;
  public int JJTJAVAIDENTIFIERINCLASSORINTERFACEDECLARATION = 18;
  public int JJTMETHODDECLARATION = 19;
  public int JJTNODE_DESC_IN_METH = 20;
  public int JJTJAVAIDENTIFIERINMETHODDECLARATOR = 21;


  public String[] jjtNodeName = {
    "void",
    "root",
    "ident_use",
    "parser_begin",
    "javacc_options",
    "option_binding",
    "javacode_production",
    "bnf_production",
    "ident_bnf_decl",
    "node_desc_bnf_decl",
    "regular_expr_production",
    "token_manager_decls",
    "regexpr_kind",
    "regexpr_spec",
    "node_desc_in_exp",
    "ident_reg_expr_label",
    "ident_reg_expr_private_label",
    "ClassOrInterfaceDeclaration",
    "JavaIdentifierInClassOrInterfaceDeclaration",
    "MethodDeclaration",
    "node_desc_in_meth",
    "JavaIdentifierInMethodDeclarator",
  };
}
/* JavaCC - OriginalChecksum=be2b1b2930368b7ad02b0545fda4ca83 (do not edit this line) */
