/* Generated By:JJTree: Do not edit this line. ASTjavacc_options.java */

package sf.eclipse.javacc.parser;

public class ASTjavacc_options extends SimpleNode {
  public ASTjavacc_options(int id) {
    super(id);
  }

  public ASTjavacc_options(JavaCCParser p, int id) {
    super(p, id);
  }

}
