/* Generated By:JJTree: Do not edit this line. ASToptionss.java */

package sf.eclipse.javacc.parser;

public class ASToptionss extends SimpleNode {
  public ASToptionss(int id) {
    super(id);
  }

  public ASToptionss(JavaCCParser p, int id) {
    super(p, id);
  }

}
