/* Generated By:JJTree: Do not edit this line. ASToption.java */

package sf.eclipse.javacc.parser;

public class ASToption extends SimpleNode {
  public ASToption(int id) {
    super(id);
  }

  public ASToption(JavaCCParser p, int id) {
    super(p, id);
  }

}
