/* Generated By:JJTree: Do not edit this line. ASTproduction.java */

package sf.eclipse.javacc.parser;

public class ASTproduction extends SimpleNode {
  public ASTproduction(int id) {
    super(id);
  }

  public ASTproduction(JavaCCParser p, int id) {
    super(p, id);
  }
  public String getName() {
    return first.next.image;
  }
}
