/* Generated By:JJTree: Do not edit this line. ASTrule.java */

package sf.eclipse.javacc.parser;

public class ASTrule extends SimpleNode {
  public ASTrule(int id) {
    super(id);
  }

  public ASTrule(JavaCCParser p, int id) {
    super(p, id);
  }
  public String getName() {
    return first.next.image;
  }
}
