/* Generated By:JJTree: Do not edit this line. ASTtoken.java */

package sf.eclipse.javacc.parser;

public class ASTtoken extends SimpleNode {
  public ASTtoken(int id) {
    super(id);
  }

  public ASTtoken(JavaCCParser p, int id) {
    super(p, id);
  }
  /**
   * Strip down the tokens to get the representative one
   */
  public String toString() {
    Token token = first;
    if (first.kind == JavaCCParserConstants.LT)
      token = token.next;
    if (token.kind == JavaCCParserConstants.SHARP) // JavaCC grammar bug no ParserConstants.
      token = token.next;
    if (token.kind == JavaCCParserConstants.CLASS) 
      token = token.next;
    return token.image;
  }
}
