/* Generated By:JJTree: Do not edit this line. ASTtoken_manager_decls.java */

package sf.eclipse.javacc.parser;

public class ASTtoken_manager_decls extends SimpleNode {
  public ASTtoken_manager_decls(int id) {
    super(id);
  }

  public ASTtoken_manager_decls(JavaCCParser p, int id) {
    super(p, id);
  }

}
