/* Generated By:JJTree: Do not edit this line. ASTvoid.java */

package sf.eclipse.javacc.parser;

public class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(JavaCCParser p, int id) {
    super(p, id);
  }

}
