/* Generated By:JJTree: Do not edit this line. src\rk\eclipse\javacc\parser\JavaCCParserTreeConstants.java */

package sf.eclipse.javacc.parser;

public interface JavaCCParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTPARSER_BEGIN = 1;
  public int JJTVOID = 2;
  public int JJTOPTIONSS = 3;
  public int JJTRULE = 4;
  public int JJTTOKEN = 5;
  public int JJTTOKEN_MANAGER_DECLS = 6;
  public int JJTIDENTIFIER = 7;


  public String[] jjtNodeName = {
    "root",
    "parser_begin",
    "void",
    "optionss",
    "rule",
    "token",
    "token_manager_decls",
    "identifier",
  };
}
